spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tB8EioyHx1EeY8bxMRq
      secret-key: p3M4OSx8bhdGgp6gwU5stXNS3Fbh3c
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: ssfmall
  application:
    name: ssfmall-third-party


server:
  port: 30000